{ compiler, flags ? {}, hsPkgs, pkgs, system }:
let
    _flags = {} // flags;
    in {
      package = {
        specVersion = "1.10";
        identifier = {
          name = "SableCC2Hs";
          version = "0.0.0.1";
        };
        license = "BSD-3-Clause";
        copyright = "";
        maintainer = "Marc Fontaine <fontaine@cs.uni-duesseldorf.de>";
        author = "Marc Fontaine";
        homepage = "";
        url = "";
        synopsis = "Generate a parser (in Haskell) with the SableCC parser generator.";
        description = "This package allows one to use parsers that were written for the SableCC\nparser generator from Haskell and Prolog.\nMore specifically it reads an XML file that is generated by SableCC\n(version sablecc-3-beta.3.altgen.20041114.zip)\nand generates Haskell and Prolog modules with contain the parser tables.\nThe package also contains examples for Haskell/Prolog parsers that\nwork with these parser tables and a grammar for\nthe B specification language (as an example).\n(The B-grammar has been written by Fabian Fritz).\nWe use this tool to build front-ends for the B specification language and\nhave tested it mainly with the B-grammar.\nNevertheless there are some other SableCC grammars on the Internet\nand any feedback and bug-reports for the tool are well-come.";
        buildType = "Simple";
      };
      components = {
        SableCC2Hs = {
          depends  = [
            hsPkgs.base
            hsPkgs.containers
            hsPkgs.array
          ];
        };
        exes = {
          sableToHs = {
            depends  = [
              hsPkgs.base
              hsPkgs.containers
              hsPkgs.array
              hsPkgs.pretty
              hsPkgs.loch-th
              hsPkgs.xml
            ];
          };
        };
      };
    }