{ compiler, flags ? {}, hsPkgs, pkgs, system }:
let
    _flags = {} // flags;
    in {
      package = {
        specVersion = "0";
        identifier = {
          name = "franchise";
          version = "0.0.6";
        };
        license = "BSD-3-Clause";
        copyright = "Copyright 2008 David Roundy";
        maintainer = "David Roundy <droundy@darcs.net>";
        author = "";
        homepage = "";
        url = "";
        synopsis = "A package for configuring and building Haskell software";
        description = "Franchise is an easy-to use package for building Haskell\nsoftware.  Unlike Cabal, you aren't required to track every\npossible dependency in every possible build condition.  In\naddition, you are not required to use an external tool such as\nautoconf in order to configure the build based on which\npackages, libraries and tools are present.\nNote: the cabal dependencies are autogenerated, and approximate.";
        buildType = "Custom";
      };
      components = {
        franchise = {
          depends  = [ hsPkgs.base ];
        };
      };
    }