{ compiler, flags ? {}, hsPkgs, pkgconfPkgs, pkgs, system }:
let
    _flags = {
      splitbase = true;
    } // flags;
    in {
      flags = _flags;
      package = {
        specVersion = "1.2";
        identifier = {
          name = "prof2dot";
          version = "0.3.1";
        };
        license = "BSD-3-Clause";
        copyright = "2007, 2008 Antiope Associates LLC";
        maintainer = "gwright@antiope.com";
        author = "Gregory Wright";
        homepage = "http://antiope.com/downloads.html";
        url = "";
        synopsis = "Convert GHC profiles into GraphViz's dot format";
        description = "prof2dot takes profiling information (a file generated by running\na ghc-compiled application with the +RTS -px -RTS flags) and converts it to\nGraphViz's dot format.";
        buildType = "Simple";
      };
      components = {
        exes = {
          prof2dot = {
            depends  = [
              hsPkgs.haskell98
              hsPkgs.parsec
              hsPkgs.filepath
            ] ++ (if _flags.splitbase
              then [
                hsPkgs.base
                hsPkgs.containers
              ]
              else [ hsPkgs.base ]);
          };
        };
      };
    }