{ system
, compiler
, flags ? {}
, pkgs
, hsPkgs
, pkgconfPkgs }:
  let
    _flags = {} // flags;
  in {
    flags = _flags;
    package = {
      specVersion = "1.8.0.2";
      identifier = {
        name = "api-opentheory-unicode";
        version = "1.0";
      };
      license = "MIT";
      copyright = "";
      maintainer = "Joe Leslie-Hurd <joe@gilith.com>";
      author = "Joe Leslie-Hurd <joe@gilith.com>";
      homepage = "";
      url = "";
      synopsis = "OpenTheory unicode character API";
      description = "This package provides an API to the unicode character package\nopentheory-unicode which is automatically generated by OpenTheory.";
      buildType = "Simple";
    };
    components = {
      "api-opentheory-unicode" = {
        depends  = [
          (hsPkgs.base)
          (hsPkgs.bytestring)
          (hsPkgs.opentheory-unicode)
        ];
      };
      exes = {
        "api-opentheory-unicode-test" = {
          depends  = [
            (hsPkgs.base)
            (hsPkgs.bytestring)
            (hsPkgs.directory)
            (hsPkgs.opentheory-unicode)
          ];
        };
      };
    };
  }