{ system, compiler, flags, pkgs, hsPkgs, pkgconfPkgs, ... }:
  {
    flags = {};
    package = {
      specVersion = "1.8";
      identifier = { name = "aterm-utils"; version = "0.2.0.0"; };
      license = "BSD-3-Clause";
      copyright = "(c) 2012 Galois, Inc";
      maintainer = "dagit@galois.com";
      author = "Jason Dagit";
      homepage = "https://github.com/GaloisInc/aterm-utils";
      url = "";
      synopsis = "Utility functions for working with aterms as generated by Minitermite";
      description = "";
      buildType = "Simple";
      };
    components = {
      "library" = {
        depends = [
          (hsPkgs."base" or ((hsPkgs.pkgs-errors).buildDepError "base"))
          (hsPkgs."aterm" or ((hsPkgs.pkgs-errors).buildDepError "aterm"))
          (hsPkgs."mtl" or ((hsPkgs.pkgs-errors).buildDepError "mtl"))
          (hsPkgs."transformers" or ((hsPkgs.pkgs-errors).buildDepError "transformers"))
          (hsPkgs."wl-pprint" or ((hsPkgs.pkgs-errors).buildDepError "wl-pprint"))
          ];
        buildable = true;
        };
      exes = {
        "ppaterm" = {
          depends = [
            (hsPkgs."base" or ((hsPkgs.pkgs-errors).buildDepError "base"))
            (hsPkgs."aterm" or ((hsPkgs.pkgs-errors).buildDepError "aterm"))
            (hsPkgs."aterm-utils" or ((hsPkgs.pkgs-errors).buildDepError "aterm-utils"))
            (hsPkgs."transformers" or ((hsPkgs.pkgs-errors).buildDepError "transformers"))
            (hsPkgs."wl-pprint" or ((hsPkgs.pkgs-errors).buildDepError "wl-pprint"))
            ];
          buildable = true;
          };
        };
      };
    }