{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  {
    flags = {};
    package = {
      specVersion = "1.8";
      identifier = { name = "aterm-utils"; version = "0.1.0.0"; };
      license = "BSD-3-Clause";
      copyright = "(c) 2012 Galois, Inc ";
      maintainer = "dagit@galois.com";
      author = "Jason Dagit";
      homepage = "https://github.com/GaloisInc/aterm-utils";
      url = "";
      synopsis = "Utility functions for working with aterms as generated by Minitermite";
      description = "";
      buildType = "Simple";
    };
    components = {
      "library" = {
        depends = [
          (hsPkgs."base" or (errorHandler.buildDepError "base"))
          (hsPkgs."aterm" or (errorHandler.buildDepError "aterm"))
          (hsPkgs."transformers" or (errorHandler.buildDepError "transformers"))
          (hsPkgs."wl-pprint" or (errorHandler.buildDepError "wl-pprint"))
        ];
        buildable = true;
      };
      exes = {
        "ppaterm" = {
          depends = [
            (hsPkgs."base" or (errorHandler.buildDepError "base"))
            (hsPkgs."aterm" or (errorHandler.buildDepError "aterm"))
            (hsPkgs."aterm-utils" or (errorHandler.buildDepError "aterm-utils"))
            (hsPkgs."transformers" or (errorHandler.buildDepError "transformers"))
            (hsPkgs."wl-pprint" or (errorHandler.buildDepError "wl-pprint"))
          ];
          buildable = true;
        };
      };
    };
  }