{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  {
    flags = {};
    package = {
      specVersion = "1.20";
      identifier = { name = "autom"; version = "0.1.0.1"; };
      license = "GPL-3.0-only";
      copyright = "";
      maintainer = "ch.howard@zoho.com";
      author = "Christopher Howard";
      homepage = "https://qlfiles.net/the-ql-files/next-nearest-neighbors-cellular-automata";
      url = "";
      synopsis = "Generates and displays patterns from next nearest neighbors cellular automata";
      description = "This library is essentially a reimplementation of the\npattern generation algorithm described in\nWentlian Li's 1998 article COMPLEX PATTERNS\nGENERATED BY NEXT NEAREST NEIGHBORDS CELLULAR\nAUTONOMA (Choas and Fractals: A Computer\nGraphical Journey). This algorithm allows one to\ngenerate an amazing pattern (sometimes with\nfractal characteristics) by simply specifying a\n32-bit integer. Please visit the project homepage\nfor more information along with example images.";
      buildType = "Simple";
      };
    components = {
      "library" = {
        depends = [
          (hsPkgs."base" or (errorHandler.buildDepError "base"))
          (hsPkgs."vector" or (errorHandler.buildDepError "vector"))
          (hsPkgs."bytestring" or (errorHandler.buildDepError "bytestring"))
          (hsPkgs."gloss" or (errorHandler.buildDepError "gloss"))
          (hsPkgs."random" or (errorHandler.buildDepError "random"))
          (hsPkgs."colour" or (errorHandler.buildDepError "colour"))
          (hsPkgs."ghc-prim" or (errorHandler.buildDepError "ghc-prim"))
          (hsPkgs."JuicyPixels" or (errorHandler.buildDepError "JuicyPixels"))
          ];
        buildable = true;
        };
      };
    }