{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  {
    flags = { buildexamples = false; };
    package = {
      specVersion = "1.12";
      identifier = { name = "blas-ffi"; version = "0.1"; };
      license = "BSD-3-Clause";
      copyright = "";
      maintainer = "Henning Thielemann <haskell@henning-thielemann.de>";
      author = "Henning Thielemann <haskell@henning-thielemann.de>";
      homepage = "http://hub.darcs.net/thielema/blas-ffi/";
      url = "";
      synopsis = "Auto-generated interface to Fortran BLAS";
      description = "BLAS is a package for efficient basic linear algebra operations.\nThe reference implementation is written in FORTRAN.\n\nThis is an automatically generated low-level interface.\nWe provide bindings to functions of all variants\nfor @Float@, @Double@, @Complex Float@ and @Complex Double@.\nWe do not use TemplateHaskell nor HSC nor CHS,\nbut instead Haskell 98 code\ngenerated by the custom @lapack-ffi-tools@ package.";
      buildType = "Simple";
    };
    components = {
      "library" = {
        depends = [
          (hsPkgs."netlib-ffi" or (errorHandler.buildDepError "netlib-ffi"))
          (hsPkgs."base" or (errorHandler.buildDepError "base"))
        ];
        pkgconfig = [
          (pkgconfPkgs."blas" or (errorHandler.pkgConfDepError "blas"))
        ];
        buildable = true;
      };
      exes = {
        "blas-demo" = {
          depends = pkgs.lib.optionals (flags.buildexamples) [
            (hsPkgs."storable-complex" or (errorHandler.buildDepError "storable-complex"))
            (hsPkgs."blas-ffi" or (errorHandler.buildDepError "blas-ffi"))
            (hsPkgs."base" or (errorHandler.buildDepError "base"))
          ];
          buildable = if flags.buildexamples then true else false;
        };
      };
    };
  }