{ system, compiler, flags, pkgs, hsPkgs, pkgconfPkgs, ... }:
  {
    flags = { exe = true; license-report = false; _ = false; };
    package = {
      specVersion = "2.2";
      identifier = { name = "cabal-plan"; version = "0.5.0.0"; };
      license = "GPL-2.0-or-later AND BSD-3-Clause";
      copyright = "2016 Herbert Valerio Riedel";
      maintainer = "hvr@gnu.org";
      author = "Herbert Valerio Riedel";
      homepage = "";
      url = "";
      synopsis = "Library and utility for processing cabal's plan.json file";
      description = "This package provides a library (see \"Cabal.Plan\") for decoding @plan.json@ files as\nwell as the simple tool @cabal-plan@ for extracting and pretty printing\nthe information contained in the @plan.json@ file.\n\n@plan.json@ files are generated by [cabal](https://hackage.haskell.org/package/cabal-install)'s [Nix-style local builds](http://cabal.readthedocs.io/en/latest/nix-local-build.html) and contain detailed information about the build/install plan computed by the cabal solver.\n\n== @cabal-plan@ utility\n\nThe @cabal-plan@ executable (enabled via the @exe@ cabal flag) provides various operations:\n\n[info] Show basic report of dependency tree\n[show] Dump 'PlanJson' data-structure via 'Show' instance\n[list-bins] List all binaries\n[list-bin] List single binary (useful for scripting, e.g. @cabal list-bin exe:cabal-plan@)\n[fingerprint] Print SHA256 sums of dependencies' source tarballs and cabal files\n[dot] Generate graph of dependencies in @.dot@ format\n[topo] Print plan topologically sorted\n[license-report] Generate license report for a component (only available when built with @license-report@ flag enabled); see <src/example/cabal-plan.md report example for cabal-plan> (<src/example/cabal-plan.html Pandoc rendered HTML>)\n\nSee also [\"New things in Haskell package QA\" Blogpost](http://oleg.fi/gists/posts/2018-01-08-haskell-package-qa.html) for a description of the @topo@ and @dot@ operations as well as how to enable tab-completion.";
      buildType = "Simple";
      };
    components = {
      "library" = {
        depends = [
          (hsPkgs.base)
          (hsPkgs.aeson)
          (hsPkgs.bytestring)
          (hsPkgs.containers)
          (hsPkgs.text)
          (hsPkgs.directory)
          (hsPkgs.filepath)
          (hsPkgs.base16-bytestring)
          ];
        };
      sublibs = {
        "topograph" = {
          depends = [
            (hsPkgs.base)
            (hsPkgs.base-compat)
            (hsPkgs.base-orphans)
            (hsPkgs.containers)
            (hsPkgs.vector)
            ];
          };
        };
      exes = {
        "cabal-plan" = {
          depends = (pkgs.lib).optionals (flags.exe) (([
            (hsPkgs.cabal-plan)
            (hsPkgs.topograph)
            (hsPkgs.base)
            (hsPkgs.text)
            (hsPkgs.containers)
            (hsPkgs.bytestring)
            (hsPkgs.directory)
            (hsPkgs.mtl)
            (hsPkgs.ansi-terminal)
            (hsPkgs.base-compat)
            (hsPkgs.optparse-applicative)
            (hsPkgs.parsec)
            (hsPkgs.vector)
            ] ++ (pkgs.lib).optionals (flags.license-report) [
            (hsPkgs.Cabal)
            (hsPkgs.tar)
            (hsPkgs.zlib)
            (hsPkgs.filepath)
            ]) ++ (pkgs.lib).optional (!(compiler.isGhc && (compiler.version).ge "8.0")) (hsPkgs.semigroups));
          };
        };
      };
    }