let
  buildDepError = pkg:
    builtins.throw ''
      The Haskell package set does not contain the package: ${pkg} (build dependency).
      
      If you are using Stackage, make sure that you are using a snapshot that contains the package. Otherwise you may need to update the Hackage snapshot you are using, usually by updating haskell.nix.
      '';
  sysDepError = pkg:
    builtins.throw ''
      The Nixpkgs package set does not contain the package: ${pkg} (system dependency).
      
      You may need to augment the system package mapping in haskell.nix so that it can be found.
      '';
  pkgConfDepError = pkg:
    builtins.throw ''
      The pkg-conf packages does not contain the package: ${pkg} (pkg-conf dependency).
      
      You may need to augment the pkg-conf package mapping in haskell.nix so that it can be found.
      '';
  exeDepError = pkg:
    builtins.throw ''
      The local executable components do not include the component: ${pkg} (executable dependency).
      '';
  legacyExeDepError = pkg:
    builtins.throw ''
      The Haskell package set does not contain the package: ${pkg} (executable dependency).
      
      If you are using Stackage, make sure that you are using a snapshot that contains the package. Otherwise you may need to update the Hackage snapshot you are using, usually by updating haskell.nix.
      '';
  buildToolDepError = pkg:
    builtins.throw ''
      Neither the Haskell package set or the Nixpkgs package set contain the package: ${pkg} (build tool dependency).
      
      If this is a system dependency:
      You may need to augment the system package mapping in haskell.nix so that it can be found.
      
      If this is a Haskell dependency:
      If you are using Stackage, make sure that you are using a snapshot that contains the package. Otherwise you may need to update the Hackage snapshot you are using, usually by updating haskell.nix.
      '';
in { system, compiler, flags, pkgs, hsPkgs, pkgconfPkgs, ... }:
  {
    flags = {};
    package = {
      specVersion = "1.10";
      identifier = { name = "casadi-bindings"; version = "2.1.0.0"; };
      license = "LGPL-3.0-only";
      copyright = "(c) Greg Horn 2013-2014";
      maintainer = "gregmainland@gmail.com";
      author = "Greg Horn";
      homepage = "http://github.com/ghorn/casadi-bindings";
      url = "";
      synopsis = "mid-level bindings to CasADi";
      description = "Haskell bindings to the CasADi algorithmic differentiation and optimal control library.\nVersion numbers correspond to the C++ library version numbers except the very last number\nwhich may indicate breaking changes.\n\nThis package is a mid-level interface to the low-level bindings `casadi-bindings-core`.\n\nThe `casadi-bindings-internal` package is handwritten and provides some casadi memory management\nwrappers and C++ standard type marsahalling.\n\nThe module `casadi-bindings-core` is autogenerated\nfrom casadi's swig interface and corresponds to the casadi C++ API\n(though some functions will be missing).\n\nFor high-level bindings, see my <https://github.com/ghorn/dynobud dynobud> project\n\nThe current instructions for getting started on Debian/Ubuntu:\n\nInstall casadi from source or with apt-get for debian or homebrew for osx (IN PROGRESS)\n\n>> apt-get install libcasadi*\n\nThen cabal install this package\n\n>> cabal update; cabal install casadi-bindings";
      buildType = "Simple";
      };
    components = {
      "library" = {
        depends = [
          (hsPkgs."base" or (buildDepError "base"))
          (hsPkgs."linear" or (buildDepError "linear"))
          (hsPkgs."vector" or (buildDepError "vector"))
          (hsPkgs."containers" or (buildDepError "containers"))
          (hsPkgs."casadi-bindings-internal" or (buildDepError "casadi-bindings-internal"))
          (hsPkgs."casadi-bindings-core" or (buildDepError "casadi-bindings-core"))
          ];
        };
      };
    }