{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  {
    flags = {};
    package = {
      specVersion = "1.0";
      identifier = { name = "dfsbuild"; version = "1.0.1"; };
      license = "LicenseRef-GPL";
      copyright = "Copyright (c) 2006-2007 John Goerzen";
      maintainer = "John Goerzen <jgoerzen@complete.org>";
      author = "John Goerzen";
      homepage = "";
      url = "";
      synopsis = "Build Debian From Scratch CD/DVD images";
      description = "Debian From Scratch (DFS) is a live bootable CD that is designed to\nprovide a fully-featured kernel and a fully-featured rescue environment.\nThe rescue environment contains filesystem tools, editors, C development\nenvironment, etc.\n\ndfsbuild is the program used to create the DFS CD image.  It is highly\nconfigurable and can be used to create other custom bootable CD or DVD\nimages.  You can use dfsbuild to do something as simple as building a\nDFS CD with a custom kernel.  Or, you can customize the CD to include a\ncompletely different set of packages.\n\ndfsbuild works by obtaining packages from your nearest Debian mirror.\nIt will generate an ISO image that contains a bootable Debian system\ngenerated by installing those packages.  Also, it can place all the .debs\nand files needed by cdebootstrap in the image.  Thus, the\ngenerated image can be used to install the base Debian system on a PC as\nwell.\n\nOn i386 and amd64 platforms, dfsbuild supports the Grub bootloader.\n\nOn Alpha, dfsbuild supports the aboot bootloader.\n\nOn PowerPC, dfsbuild supports the yaboot bootloader.";
      buildType = "Custom";
      };
    components = {
      exes = {
        "dfsbuild" = {
          depends = [
            (hsPkgs."base" or (errorHandler.buildDepError "base"))
            (hsPkgs."network" or (errorHandler.buildDepError "network"))
            (hsPkgs."unix" or (errorHandler.buildDepError "unix"))
            (hsPkgs."parsec" or (errorHandler.buildDepError "parsec"))
            (hsPkgs."MissingH" or (errorHandler.buildDepError "MissingH"))
            (hsPkgs."regex-compat" or (errorHandler.buildDepError "regex-compat"))
            (hsPkgs."hslogger" or (errorHandler.buildDepError "hslogger"))
            (hsPkgs."filepath" or (errorHandler.buildDepError "filepath"))
            (hsPkgs."ConfigFile" or (errorHandler.buildDepError "ConfigFile"))
            (hsPkgs."HSH" or (errorHandler.buildDepError "HSH"))
            ];
          buildable = true;
          };
        };
      };
    }