{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  {
    flags = {};
    package = {
      specVersion = "1.8";
      identifier = { name = "fay-hsx"; version = "0.2.0"; };
      license = "BSD-3-Clause";
      copyright = "2013, SeeReason Partners LLC";
      maintainer = "jeremy@n-heptane.com";
      author = "Jeremy Shaw";
      homepage = "http://www.happstack.com/";
      url = "";
      synopsis = "Clientside HTML generation for fay.";
      description = "This library allows you to write fay code that generates HTML in the browser. It is compatible with the code generated by hsx2hs.";
      buildType = "Simple";
      };
    components = {
      "library" = {
        depends = [
          (hsPkgs."fay-base" or (errorHandler.buildDepError "fay-base"))
          (hsPkgs."fay-jquery" or (errorHandler.buildDepError "fay-jquery"))
          ];
        buildable = true;
        };
      };
    }