{ system, compiler, flags, pkgs, hsPkgs, pkgconfPkgs, ... }:
  {
    flags = {};
    package = {
      specVersion = "1.10";
      identifier = { name = "fptest"; version = "0.2.2.0"; };
      license = "BSD-3-Clause";
      copyright = "2014 John Pavel and 2004 IBM Corp";
      maintainer = "jrp@dial.pipex.com";
      author = "John Pavel";
      homepage = "https://github.com/jrp2014/fptest";
      url = "";
      synopsis = "IEEE754r floating point conformance tests";
      description = "A series of floating point conformance tests for Haskell.\nCurrently implemented are:\nQTrial, the floating point benchmark described in / IEEE Standard 754 for Binary Floating-Point\nArithmetic / by Prof. W. Kahan <http://www.eecs.berkeley.edu/~wkahan/ieee754status/IEEE754.PDF>\nThis can be run with a simple @cabal run qtrial@.\nFPTest runs a sequence of floating point test vectors generated by IBM's\n<https://www.research.ibm.com/haifa/projects/verification/fpgen/ FPGen Floating-Point Test Generator>.\nThis is done either by interpreting the tests or by translating the tests\ninto a Haskell HUnit test suite script that can just be executed using\n@runhaskell@.\nThe IBM test vectors are available from\n<https://www.research.ibm.com/haifa/projects/verification/fpgen/ here>.\nYou will, most likely, want the binary tests unless you have a decimal machine.\nOnly 32-bit float tests are provided (not 64-bit double ones) although FPTest supports Doubles.\nThe syntax of the test vectors can be found\n<https://www.research.ibm.com/haifa/projects/verification/fpgen/syntax.txt here> or in Chapter 4\n<https://www.research.ibm.com/haifa/projects/verification/fpgen/papers/ieee-test-suite-v2.pdfs\nFloating-Point Test-Suite for IEEE here>";
      buildType = "Simple";
      };
    components = {
      exes = {
        "qtrial" = {
          depends = [
            (hsPkgs.base)
            (hsPkgs.test-framework)
            (hsPkgs.test-framework-hunit)
            (hsPkgs.HUnit)
            (hsPkgs.parsec3-numbers)
            (hsPkgs.QuickCheck)
            (hsPkgs.test-framework-quickcheck2)
            ];
          };
        "fptest" = {
          depends = [
            (hsPkgs.base)
            (hsPkgs.parsec)
            (hsPkgs.test-framework)
            (hsPkgs.test-framework-hunit)
            (hsPkgs.HUnit)
            (hsPkgs.parsec3-numbers)
            (hsPkgs.QuickCheck)
            (hsPkgs.test-framework-quickcheck2)
            ];
          };
        };
      tests = {
        "qtrial-quickcheck" = {
          depends = [
            (hsPkgs.base)
            (hsPkgs.parsec)
            (hsPkgs.test-framework)
            (hsPkgs.test-framework-hunit)
            (hsPkgs.HUnit)
            (hsPkgs.parsec3-numbers)
            (hsPkgs.QuickCheck)
            (hsPkgs.test-framework-quickcheck2)
            ];
          };
        "fptest-quickcheck" = {
          depends = [
            (hsPkgs.base)
            (hsPkgs.parsec)
            (hsPkgs.test-framework)
            (hsPkgs.test-framework-hunit)
            (hsPkgs.HUnit)
            (hsPkgs.parsec3-numbers)
            (hsPkgs.QuickCheck)
            (hsPkgs.test-framework-quickcheck2)
            ];
          };
        "doctest" = {
          depends = [ (hsPkgs.base) (hsPkgs.doctest) (hsPkgs.Glob) ];
          };
        "haddock" = {
          depends = [ (hsPkgs.base) (hsPkgs.process) (hsPkgs.regex-compat) ];
          };
        "hlint" = { depends = [ (hsPkgs.base) (hsPkgs.hlint) ]; };
        };
      };
    }