{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  {
    flags = {};
    package = {
      specVersion = "1.12";
      identifier = { name = "futhask-base"; version = "0.1.0.0"; };
      license = "BSD-3-Clause";
      copyright = "2026 Gusten Isfeldt";
      maintainer = "isfeldt@kth.se";
      author = "Gusten Isfeldt";
      homepage = "https://gitlab.com/Gusten_Isfeldt/futhask#readme";
      url = "";
      synopsis = "Base library for libraries generated by futhask";
      description = "This package contains various class definitions and utility functions\nused in libraries generated by futhask.\nFuthask is an FFI tool that creates haskell libraries from futhark libraries\nthrough the futhark C-API, aiming to create a safe, haskell friendly,\ninterface for high performance computation.";
      buildType = "Simple";
    };
    components = {
      "library" = {
        depends = [
          (hsPkgs."base" or (errorHandler.buildDepError "base"))
          (hsPkgs."array" or (errorHandler.buildDepError "array"))
          (hsPkgs."bytestring" or (errorHandler.buildDepError "bytestring"))
          (hsPkgs."monad-control" or (errorHandler.buildDepError "monad-control"))
          (hsPkgs."mtl" or (errorHandler.buildDepError "mtl"))
          (hsPkgs."transformers-base" or (errorHandler.buildDepError "transformers-base"))
          (hsPkgs."half" or (errorHandler.buildDepError "half"))
          (hsPkgs."text" or (errorHandler.buildDepError "text"))
        ];
        buildable = true;
      };
    };
  }