{ system, compiler, flags, pkgs, hsPkgs, pkgconfPkgs, ... }:
  {
    flags = {};
    package = {
      specVersion = "1.24";
      identifier = { name = "gi-gtkosxapplication"; version = "2.0.17"; };
      license = "LGPL-2.1-only";
      copyright = "";
      maintainer = "Iñaki García Etxebarria";
      author = "Will Thompson, Iñaki García Etxebarria and Jonas Platte";
      homepage = "https://github.com/haskell-gi/haskell-gi";
      url = "";
      synopsis = "GtkosxApplication bindings";
      description = "Bindings for GtkosxApplication (provided by gtk-mac-integration), autogenerated by haskell-gi.";
      buildType = "Custom";
      setup-depends = [
        (hsPkgs.buildPackages.base or (pkgs.buildPackages.base))
        (hsPkgs.buildPackages.Cabal or (pkgs.buildPackages.Cabal))
        (hsPkgs.buildPackages.haskell-gi or (pkgs.buildPackages.haskell-gi))
        (hsPkgs.buildPackages.gi-gtk or (pkgs.buildPackages.gi-gtk))
        (hsPkgs.buildPackages.gi-gdkpixbuf or (pkgs.buildPackages.gi-gdkpixbuf))
        (hsPkgs.buildPackages.gi-gobject or (pkgs.buildPackages.gi-gobject))
        ];
      };
    components = {
      "library" = {
        depends = [
          (hsPkgs.base)
          (hsPkgs.haskell-gi-base)
          (hsPkgs.haskell-gi)
          (hsPkgs.haskell-gi-overloading)
          (hsPkgs.gi-gtk)
          (hsPkgs.gi-gdkpixbuf)
          (hsPkgs.gi-gobject)
          (hsPkgs.bytestring)
          (hsPkgs.containers)
          (hsPkgs.text)
          (hsPkgs.transformers)
          ] ++ (pkgs.lib).optional (compiler.isGhc && false) (hsPkgs.haskell-gi-overloading);
        pkgconfig = [ (pkgconfPkgs."gtk-mac-integration-gtk3") ];
        };
      };
    }