{ system, compiler, flags, pkgs, hsPkgs, pkgconfPkgs, ... }:
  {
    flags = {};
    package = {
      specVersion = "1.24";
      identifier = { name = "gi-gdkx11"; version = "3.0.9"; };
      license = "LGPL-2.1-only";
      copyright = "";
      maintainer = "Iñaki García Etxebarria";
      author = "Will Thompson, Iñaki García Etxebarria and Jonas Platte";
      homepage = "https://github.com/haskell-gi/haskell-gi";
      url = "";
      synopsis = "GdkX11 bindings";
      description = "Bindings for GdkX11, autogenerated by haskell-gi.";
      buildType = "Custom";
      setup-depends = [
        (hsPkgs.buildPackages.base or (pkgs.buildPackages.base))
        (hsPkgs.buildPackages.Cabal or (pkgs.buildPackages.Cabal))
        (hsPkgs.buildPackages.haskell-gi or (pkgs.buildPackages.haskell-gi))
        (hsPkgs.buildPackages.gi-gobject or (pkgs.buildPackages.gi-gobject))
        (hsPkgs.buildPackages.gi-gdk or (pkgs.buildPackages.gi-gdk))
        (hsPkgs.buildPackages.gi-gio or (pkgs.buildPackages.gi-gio))
        (hsPkgs.buildPackages.gi-cairo or (pkgs.buildPackages.gi-cairo))
        (hsPkgs.buildPackages.gi-xlib or (pkgs.buildPackages.gi-xlib))
        ];
      };
    components = {
      "library" = {
        depends = [
          (hsPkgs.base)
          (hsPkgs.haskell-gi-base)
          (hsPkgs.haskell-gi)
          (hsPkgs.haskell-gi-overloading)
          (hsPkgs.gi-gobject)
          (hsPkgs.gi-gdk)
          (hsPkgs.gi-gio)
          (hsPkgs.gi-cairo)
          (hsPkgs.gi-xlib)
          (hsPkgs.bytestring)
          (hsPkgs.containers)
          (hsPkgs.text)
          (hsPkgs.transformers)
          ] ++ (pkgs.lib).optional (compiler.isGhc && false) (hsPkgs.haskell-gi-overloading);
        pkgconfig = [ (pkgconfPkgs."gdk-x11-3.0") ];
        };
      };
    }