{ system, compiler, flags, pkgs, hsPkgs, pkgconfPkgs, ... }:
  {
    flags = {};
    package = {
      specVersion = "1.24";
      identifier = { name = "gi-handy"; version = "0.0.5"; };
      license = "LGPL-2.1-only";
      copyright = "";
      maintainer = "Iñaki García Etxebarria (inaki@blueleaf.cc)";
      author = "Will Thompson, Iñaki García Etxebarria and Jonas Platte";
      homepage = "https://github.com/haskell-gi/haskell-gi";
      url = "";
      synopsis = "libhandy bindings";
      description = "Bindings for libhandy, autogenerated by haskell-gi.";
      buildType = "Custom";
      setup-depends = [
        (hsPkgs.buildPackages.base or (pkgs.buildPackages.base))
        (hsPkgs.buildPackages.Cabal or (pkgs.buildPackages.Cabal))
        (hsPkgs.buildPackages.haskell-gi or (pkgs.buildPackages.haskell-gi))
        (hsPkgs.buildPackages.gi-gtk or (pkgs.buildPackages.gi-gtk))
        (hsPkgs.buildPackages.gi-gdk or (pkgs.buildPackages.gi-gdk))
        (hsPkgs.buildPackages.gi-atk or (pkgs.buildPackages.gi-atk))
        (hsPkgs.buildPackages.gi-gobject or (pkgs.buildPackages.gi-gobject))
        (hsPkgs.buildPackages.gi-glib or (pkgs.buildPackages.gi-glib))
        (hsPkgs.buildPackages.gi-gio or (pkgs.buildPackages.gi-gio))
        ];
      };
    components = {
      "library" = {
        depends = [
          (hsPkgs.base)
          (hsPkgs.haskell-gi-base)
          (hsPkgs.haskell-gi)
          (hsPkgs.haskell-gi-overloading)
          (hsPkgs.gi-gtk)
          (hsPkgs.gi-gdk)
          (hsPkgs.gi-atk)
          (hsPkgs.gi-gobject)
          (hsPkgs.gi-glib)
          (hsPkgs.gi-gio)
          (hsPkgs.bytestring)
          (hsPkgs.containers)
          (hsPkgs.text)
          (hsPkgs.transformers)
          ] ++ (pkgs.lib).optional (compiler.isGhc && false) (hsPkgs.haskell-gi-overloading);
        pkgconfig = [ (pkgconfPkgs."libhandy-0.0") ];
        };
      };
    }