{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  {
    flags = {};
    package = {
      specVersion = "2.0";
      identifier = {
        name = "gi-webkitwebprocessextension";
        version = "6.0.3";
      };
      license = "LGPL-2.1-only";
      copyright = "";
      maintainer = "Iñaki García Etxebarria";
      author = "Iñaki García Etxebarria";
      homepage = "https://github.com/haskell-gi/haskell-gi";
      url = "";
      synopsis = "WebKitWebProcessExtension bindings";
      description = "Bindings for WebKitWebProcessExtension, autogenerated by haskell-gi.";
      buildType = "Custom";
      setup-depends = [
        (hsPkgs.pkgsBuildBuild.base or (pkgs.pkgsBuildBuild.base or (errorHandler.setupDepError "base")))
        (hsPkgs.pkgsBuildBuild.Cabal or (pkgs.pkgsBuildBuild.Cabal or (errorHandler.setupDepError "Cabal")))
        (hsPkgs.pkgsBuildBuild.haskell-gi or (pkgs.pkgsBuildBuild.haskell-gi or (errorHandler.setupDepError "haskell-gi")))
        (hsPkgs.pkgsBuildBuild.gi-soup or (pkgs.pkgsBuildBuild.gi-soup or (errorHandler.setupDepError "gi-soup")))
        (hsPkgs.pkgsBuildBuild.gi-gio or (pkgs.pkgsBuildBuild.gi-gio or (errorHandler.setupDepError "gi-gio")))
        (hsPkgs.pkgsBuildBuild.gi-javascriptcore or (pkgs.pkgsBuildBuild.gi-javascriptcore or (errorHandler.setupDepError "gi-javascriptcore")))
        (hsPkgs.pkgsBuildBuild.gi-gdk or (pkgs.pkgsBuildBuild.gi-gdk or (errorHandler.setupDepError "gi-gdk")))
        (hsPkgs.pkgsBuildBuild.gi-gtk or (pkgs.pkgsBuildBuild.gi-gtk or (errorHandler.setupDepError "gi-gtk")))
        (hsPkgs.pkgsBuildBuild.gi-gobject or (pkgs.pkgsBuildBuild.gi-gobject or (errorHandler.setupDepError "gi-gobject")))
      ];
    };
    components = {
      "library" = {
        depends = [
          (hsPkgs."base" or (errorHandler.buildDepError "base"))
          (hsPkgs."haskell-gi-base" or (errorHandler.buildDepError "haskell-gi-base"))
          (hsPkgs."haskell-gi" or (errorHandler.buildDepError "haskell-gi"))
          (hsPkgs."haskell-gi-overloading" or (errorHandler.buildDepError "haskell-gi-overloading"))
          (hsPkgs."gi-soup" or (errorHandler.buildDepError "gi-soup"))
          (hsPkgs."gi-gio" or (errorHandler.buildDepError "gi-gio"))
          (hsPkgs."gi-javascriptcore" or (errorHandler.buildDepError "gi-javascriptcore"))
          (hsPkgs."gi-gdk" or (errorHandler.buildDepError "gi-gdk"))
          (hsPkgs."gi-gtk" or (errorHandler.buildDepError "gi-gtk"))
          (hsPkgs."gi-gobject" or (errorHandler.buildDepError "gi-gobject"))
          (hsPkgs."bytestring" or (errorHandler.buildDepError "bytestring"))
          (hsPkgs."containers" or (errorHandler.buildDepError "containers"))
          (hsPkgs."text" or (errorHandler.buildDepError "text"))
          (hsPkgs."transformers" or (errorHandler.buildDepError "transformers"))
        ] ++ pkgs.lib.optional (compiler.isGhc && (compiler.version.ge "8.2" && compiler.version.lt "8.3")) (hsPkgs."haskell-gi-overloading" or (errorHandler.buildDepError "haskell-gi-overloading"));
        pkgconfig = [
          (pkgconfPkgs."webkitgtk-web-process-extension-6.0" or (errorHandler.pkgConfDepError "webkitgtk-web-process-extension-6.0"))
        ];
        buildable = true;
      };
    };
  }