{ system
, compiler
, flags
, pkgs
, hsPkgs
, pkgconfPkgs }:
  {
    flags = {};
    package = {
      specVersion = "1.10";
      identifier = {
        name = "gloss-sodium";
        version = "0.1.0.0";
      };
      license = "AGPL-3.0-only";
      copyright = "";
      maintainer = "twey@twey.co.uk";
      author = "James ‘Twey’ Kay";
      homepage = "https://github.com/Twey/gloss-sodium";
      url = "";
      synopsis = "A Sodium interface to the Gloss drawing package.";
      description = "This package exports a simple wrapper, in terms of\nGraphics.Gloss.Interface.IO.Game, that allows full\ncontrol of the picture generated by Gloss as a\nBehavior, as well as providing access to\nGloss' clock and input-handling functionality as\nEvents.";
      buildType = "Simple";
    };
    components = {
      "gloss-sodium" = {
        depends  = [
          (hsPkgs.base)
          (hsPkgs.gloss)
          (hsPkgs.sodium)
        ];
      };
    };
  }