{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  {
    flags = {};
    package = {
      specVersion = "1.12";
      identifier = { name = "gtfs-realtime"; version = "0.2.0.0"; };
      license = "BSD-3-Clause";
      copyright = "Cthulhu (c) 2018";
      maintainer = "cthulhu.den@gmail.com";
      author = "Cthulhu";
      homepage = "https://github.com/CthulhuDen/gtfs-realtime#readme";
      url = "";
      synopsis = "GTFS RealTime protobafs library (autogenerated from .proto file)";
      description = "Please see the README on GitHub at <https://github.com/CthulhuDen/gtfs-realtime#readme> or <https://hackage.haskell.org/package/gtfs-realtime>";
      buildType = "Simple";
    };
    components = {
      "library" = {
        depends = [
          (hsPkgs."base" or (errorHandler.buildDepError "base"))
          (hsPkgs."protocol-buffers" or (errorHandler.buildDepError "protocol-buffers"))
          (hsPkgs."protocol-buffers-descriptor" or (errorHandler.buildDepError "protocol-buffers-descriptor"))
        ];
        buildable = true;
      };
    };
  }