{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  {
    flags = { hayoosnap4 = true; hashedindex = false; };
    package = {
      specVersion = "1.6";
      identifier = { name = "Hayoo"; version = "1.2.3"; };
      license = "MIT";
      copyright = "Copyright (c) 2007 - 2012 Uwe Schmidt, Sebastian M. Gauck and Timo B. Kranz";
      maintainer = "Timo B. Kranz <tbh@holumbus.org>, Uwe Schmidt <uwe@fh-wedel.de>";
      author = "Sebastian M. Gauck, Timo B. Kranz, Uwe Schmidt";
      homepage = "http://holumbus.fh-wedel.de";
      url = "";
      synopsis = "The Hayoo! search engine for Haskell API search on hackage";
      description = "The Hayoo! search engine based no the Holumbus framework provides a document indexer\nand a crawler to build indexes over Haddock generated API documentation and packages\nas well as a query interface for these indexes.\n\nChanges from 1.2.2: Optional use of new HashedIndex with DocIds generated by a hash function";
      buildType = "Simple";
    };
    components = {
      exes = {
        "hayooIndexer" = {
          depends = [
            (hsPkgs."base" or (errorHandler.buildDepError "base"))
            (hsPkgs."binary" or (errorHandler.buildDepError "binary"))
            (hsPkgs."bytestring" or (errorHandler.buildDepError "bytestring"))
            (hsPkgs."bzlib" or (errorHandler.buildDepError "bzlib"))
            (hsPkgs."enummapset" or (errorHandler.buildDepError "enummapset"))
            (hsPkgs."filepath" or (errorHandler.buildDepError "filepath"))
            (hsPkgs."Holumbus-Searchengine" or (errorHandler.buildDepError "Holumbus-Searchengine"))
            (hsPkgs."hxt" or (errorHandler.buildDepError "hxt"))
            (hsPkgs."hxt-cache" or (errorHandler.buildDepError "hxt-cache"))
            (hsPkgs."hxt-charproperties" or (errorHandler.buildDepError "hxt-charproperties"))
            (hsPkgs."hxt-curl" or (errorHandler.buildDepError "hxt-curl"))
            (hsPkgs."hxt-http" or (errorHandler.buildDepError "hxt-http"))
            (hsPkgs."hxt-regex-xmlschema" or (errorHandler.buildDepError "hxt-regex-xmlschema"))
            (hsPkgs."hxt-xpath" or (errorHandler.buildDepError "hxt-xpath"))
            (hsPkgs."network" or (errorHandler.buildDepError "network"))
            (hsPkgs."old-time" or (errorHandler.buildDepError "old-time"))
            (hsPkgs."parsec" or (errorHandler.buildDepError "parsec"))
            (hsPkgs."process" or (errorHandler.buildDepError "process"))
            (hsPkgs."tar" or (errorHandler.buildDepError "tar"))
            (hsPkgs."zlib" or (errorHandler.buildDepError "zlib"))
          ] ++ [
            (hsPkgs."containers" or (errorHandler.buildDepError "containers"))
            (hsPkgs."deepseq" or (errorHandler.buildDepError "deepseq"))
          ];
          buildable = true;
        };
        "hayooSnap" = {
          depends = [
            (hsPkgs."base" or (errorHandler.buildDepError "base"))
            (hsPkgs."bytestring" or (errorHandler.buildDepError "bytestring"))
            (hsPkgs."Holumbus-Searchengine" or (errorHandler.buildDepError "Holumbus-Searchengine"))
            (hsPkgs."hxt" or (errorHandler.buildDepError "hxt"))
            (hsPkgs."hxt-unicode" or (errorHandler.buildDepError "hxt-unicode"))
            (hsPkgs."json" or (errorHandler.buildDepError "json"))
            (hsPkgs."MonadCatchIO-transformers" or (errorHandler.buildDepError "MonadCatchIO-transformers"))
            (hsPkgs."mtl" or (errorHandler.buildDepError "mtl"))
            (hsPkgs."text" or (errorHandler.buildDepError "text"))
            (hsPkgs."transformers" or (errorHandler.buildDepError "transformers"))
            (hsPkgs."xhtml-combinators" or (errorHandler.buildDepError "xhtml-combinators"))
          ] ++ (if flags.hayoosnap4
            then [
              (hsPkgs."base" or (errorHandler.buildDepError "base"))
              (hsPkgs."snap" or (errorHandler.buildDepError "snap"))
              (hsPkgs."snap-core" or (errorHandler.buildDepError "snap-core"))
              (hsPkgs."snap-server" or (errorHandler.buildDepError "snap-server"))
            ]
            else [
              (hsPkgs."containers" or (errorHandler.buildDepError "containers"))
              (hsPkgs."data-lens" or (errorHandler.buildDepError "data-lens"))
              (hsPkgs."data-lens-template" or (errorHandler.buildDepError "data-lens-template"))
              (hsPkgs."filepath" or (errorHandler.buildDepError "filepath"))
              (hsPkgs."heist" or (errorHandler.buildDepError "heist"))
              (hsPkgs."snap" or (errorHandler.buildDepError "snap"))
              (hsPkgs."snap-core" or (errorHandler.buildDepError "snap-core"))
              (hsPkgs."snap-server" or (errorHandler.buildDepError "snap-server"))
            ]);
          buildable = true;
        };
      };
    };
  }