{ system, compiler, flags, pkgs, hsPkgs, pkgconfPkgs, ... }:
  {
    flags = {};
    package = {
      specVersion = "1.2";
      identifier = { name = "hurdle"; version = "0.2.0"; };
      license = "BSD-3-Clause";
      copyright = "Stephen Tetley <stephen.tetley@gmail.com>";
      maintainer = "Stephen Tetley <stephen.tetley@gmail.com>";
      author = "";
      homepage = "http://code.google.com/p/copperbox/";
      url = "";
      synopsis = "Extract function names from Windows DLLs.";
      description = "Hurdle - (H)askell (U)tilty (R)egarding (DL)l (E)xports.\n\nExtract function names from Windows DLLs a-la pexports.\n\nHurdle has minimal dependencies: base, containers, pretty and\nkangaroo (kangaroo just needs base and array).\n\nCurrently Hurdle also has minimal utility - please consider\npexports instead as Hurdle doesn't yet print ordinals\nand fails on DLLs generated by Visual C++ (Hurdle was a Sunday\nafternoon hack that took a wee bit longer). But... if anyone\nhas a compelling use case that would benefit the community, I'm\nwilling to look at extending Hurdle.\n\nChange-log\n\n0.1.0 to 0.2.0\n\n* Changed to use kangaroo binary parser combinators.\n* Added error message reporting parser failure when\n.edata section is not found.\n";
      buildType = "Simple";
      };
    components = {
      exes = {
        "hurdle" = {
          depends = [
            (hsPkgs.base)
            (hsPkgs.array)
            (hsPkgs.containers)
            (hsPkgs.pretty)
            (hsPkgs.kangaroo)
            ];
          };
        };
      };
    }