{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  {
    flags = {};
    package = {
      specVersion = "1.10";
      identifier = {
        name = "ivory-avr-atmega328p-registers";
        version = "0.1.0.0";
        };
      license = "BSD-3-Clause";
      copyright = "2020 erdeszt";
      maintainer = "erdeszt@gmail.com";
      author = "erdeszt";
      homepage = "https://github.com/erdeszt/ivory-avr-atmega328p-registers";
      url = "";
      synopsis = "Ivory register bindings for the Atmega328p";
      description = "Autogenerated ivory register bindings for the AVR Atmega328p";
      buildType = "Simple";
      };
    components = {
      "library" = {
        depends = [
          (hsPkgs."base" or (errorHandler.buildDepError "base"))
          (hsPkgs."base-compat" or (errorHandler.buildDepError "base-compat"))
          (hsPkgs."ivory" or (errorHandler.buildDepError "ivory"))
          (hsPkgs."ivory-hw" or (errorHandler.buildDepError "ivory-hw"))
          (hsPkgs."monadLib" or (errorHandler.buildDepError "monadLib"))
          ];
        buildable = true;
        };
      };
    }