let
  buildDepError = pkg:
    builtins.throw ''
      The Haskell package set does not contain the package: ${pkg} (build dependency).
      
      If you are using Stackage, make sure that you are using a snapshot that contains the package. Otherwise you may need to update the Hackage snapshot you are using, usually by updating haskell.nix.
      '';
  sysDepError = pkg:
    builtins.throw ''
      The Nixpkgs package set does not contain the package: ${pkg} (system dependency).
      
      You may need to augment the system package mapping in haskell.nix so that it can be found.
      '';
  pkgConfDepError = pkg:
    builtins.throw ''
      The pkg-conf packages does not contain the package: ${pkg} (pkg-conf dependency).
      
      You may need to augment the pkg-conf package mapping in haskell.nix so that it can be found.
      '';
  exeDepError = pkg:
    builtins.throw ''
      The local executable components do not include the component: ${pkg} (executable dependency).
      '';
  legacyExeDepError = pkg:
    builtins.throw ''
      The Haskell package set does not contain the package: ${pkg} (executable dependency).
      
      If you are using Stackage, make sure that you are using a snapshot that contains the package. Otherwise you may need to update the Hackage snapshot you are using, usually by updating haskell.nix.
      '';
  buildToolDepError = pkg:
    builtins.throw ''
      Neither the Haskell package set or the Nixpkgs package set contain the package: ${pkg} (build tool dependency).
      
      If this is a system dependency:
      You may need to augment the system package mapping in haskell.nix so that it can be found.
      
      If this is a Haskell dependency:
      If you are using Stackage, make sure that you are using a snapshot that contains the package. Otherwise you may need to update the Hackage snapshot you are using, usually by updating haskell.nix.
      '';
in { system, compiler, flags, pkgs, hsPkgs, pkgconfPkgs, ... }:
  {
    flags = {};
    package = {
      specVersion = "1.14";
      identifier = { name = "lapack-carray"; version = "0.0.2.1"; };
      license = "BSD-3-Clause";
      copyright = "";
      maintainer = "Henning Thielemann <haskell@henning-thielemann.de>";
      author = "Henning Thielemann <haskell@henning-thielemann.de>";
      homepage = "http://hub.darcs.net/thielema/lapack-carray/";
      url = "";
      synopsis = "Auto-generated interface to Fortran LAPACK via CArrays";
      description = "LAPACK is a package for efficient numerically robust linear algebra.\nThe original implementation is written in FORTRAN.\nThis is a semi-automatically generated mid-level wrapper.\nThe functions are not ready to use for high-level applications,\nbut they are a step closer.\n\nThe functions are all in IO monad because they are auto-generated and\nwe cannot make sure automatically that unsafePerformIO is always safe.\nInstead of raw pointers we use CArrays and IOCArrays\nand assign and check array bounds to LAPACK function parameters,\nas far we can retrieve this information from the FORTRAN comments.\nWe check consistency of dimensions where consistent dimensions are required,\nbut we cannot do all kind of bound checks.\nWe use immutable CArray for input and output parameters\nand mutable IOCArray for input/output parameters.\nLAPACK plays some nasty tricks of in-place array updates\non input/output arrays\neven if the dimensions of input and output array differ (see e.g. GELS).\nThe wrappers also manage allocation of memory for function parameters.\nThis is necessary since FORTRAN passes all parameters by reference.\nFurther on, the wrappers convert from Haskell values like @Int@\nto low-level values like @CInt@.\n\nWe provide bindings to functions of all variants\nfor @Float@, @Double@, @Complex Float@ and @Complex Double@.\nWe do not use TemplateHaskell nor HSC nor CHS, but instead Haskell 98 code\ngenerated by the custom @lapack-ffi-tools@ package.";
      buildType = "Simple";
      };
    components = {
      "library" = {
        depends = [
          (hsPkgs."lapack-ffi" or (buildDepError "lapack-ffi"))
          (hsPkgs."netlib-carray" or (buildDepError "netlib-carray"))
          (hsPkgs."netlib-ffi" or (buildDepError "netlib-ffi"))
          (hsPkgs."carray" or (buildDepError "carray"))
          (hsPkgs."storable-complex" or (buildDepError "storable-complex"))
          (hsPkgs."transformers" or (buildDepError "transformers"))
          (hsPkgs."base" or (buildDepError "base"))
          ];
        };
      };
    }