{ system, compiler, flags, pkgs, hsPkgs, pkgconfPkgs, ... }:
  {
    flags = {};
    package = {
      specVersion = "1.12";
      identifier = { name = "pantry"; version = "0.1.0.0"; };
      license = "BSD-3-Clause";
      copyright = "2018-2019 FP Complete";
      maintainer = "michael@snoyman.com";
      author = "Michael Snoyman";
      homepage = "https://github.com/commercialhaskell/stack#readme";
      url = "";
      synopsis = "Content addressable Haskell package management";
      description = "Please see the README on Github at <https://github.com/commercialhaskell/stack/blob/master/subs/pantry/README.md>";
      buildType = "Simple";
      };
    components = {
      "library" = {
        depends = [
          (hsPkgs.Cabal)
          (hsPkgs.aeson)
          (hsPkgs.ansi-terminal)
          (hsPkgs.array)
          (hsPkgs.base)
          (hsPkgs.base-orphans)
          (hsPkgs.base64-bytestring)
          (hsPkgs.bytestring)
          (hsPkgs.conduit)
          (hsPkgs.conduit-extra)
          (hsPkgs.containers)
          (hsPkgs.contravariant)
          (hsPkgs.cryptonite)
          (hsPkgs.cryptonite-conduit)
          (hsPkgs.deepseq)
          (hsPkgs.digest)
          (hsPkgs.directory)
          (hsPkgs.filelock)
          (hsPkgs.filepath)
          (hsPkgs.generic-deriving)
          (hsPkgs.ghc-prim)
          (hsPkgs.hackage-security)
          (hsPkgs.hashable)
          (hsPkgs.hpack)
          (hsPkgs.http-client)
          (hsPkgs.http-client-tls)
          (hsPkgs.http-conduit)
          (hsPkgs.http-download)
          (hsPkgs.http-types)
          (hsPkgs.integer-gmp)
          (hsPkgs.memory)
          (hsPkgs.mono-traversable)
          (hsPkgs.mtl)
          (hsPkgs.network)
          (hsPkgs.network-uri)
          (hsPkgs.path)
          (hsPkgs.path-io)
          (hsPkgs.persistent)
          (hsPkgs.persistent-sqlite)
          (hsPkgs.persistent-template)
          (hsPkgs.primitive)
          (hsPkgs.resourcet)
          (hsPkgs.rio)
          (hsPkgs.rio-orphans)
          (hsPkgs.rio-prettyprint)
          (hsPkgs.safe)
          (hsPkgs.syb)
          (hsPkgs.tar-conduit)
          (hsPkgs.template-haskell)
          (hsPkgs.text)
          (hsPkgs.text-metrics)
          (hsPkgs.th-lift)
          (hsPkgs.th-lift-instances)
          (hsPkgs.th-orphans)
          (hsPkgs.th-reify-many)
          (hsPkgs.th-utilities)
          (hsPkgs.time)
          (hsPkgs.transformers)
          (hsPkgs.unix-compat)
          (hsPkgs.unliftio)
          (hsPkgs.unordered-containers)
          (hsPkgs.vector)
          (hsPkgs.yaml)
          (hsPkgs.zip-archive)
          ];
        };
      tests = {
        "spec" = {
          depends = [
            (hsPkgs.Cabal)
            (hsPkgs.QuickCheck)
            (hsPkgs.aeson)
            (hsPkgs.ansi-terminal)
            (hsPkgs.array)
            (hsPkgs.base)
            (hsPkgs.base-orphans)
            (hsPkgs.base64-bytestring)
            (hsPkgs.bytestring)
            (hsPkgs.conduit)
            (hsPkgs.conduit-extra)
            (hsPkgs.containers)
            (hsPkgs.contravariant)
            (hsPkgs.cryptonite)
            (hsPkgs.cryptonite-conduit)
            (hsPkgs.deepseq)
            (hsPkgs.digest)
            (hsPkgs.directory)
            (hsPkgs.exceptions)
            (hsPkgs.filelock)
            (hsPkgs.filepath)
            (hsPkgs.generic-deriving)
            (hsPkgs.ghc-prim)
            (hsPkgs.hackage-security)
            (hsPkgs.hashable)
            (hsPkgs.hedgehog)
            (hsPkgs.hpack)
            (hsPkgs.hspec)
            (hsPkgs.http-client)
            (hsPkgs.http-client-tls)
            (hsPkgs.http-conduit)
            (hsPkgs.http-download)
            (hsPkgs.http-types)
            (hsPkgs.integer-gmp)
            (hsPkgs.memory)
            (hsPkgs.mono-traversable)
            (hsPkgs.mtl)
            (hsPkgs.network)
            (hsPkgs.network-uri)
            (hsPkgs.pantry)
            (hsPkgs.path)
            (hsPkgs.path-io)
            (hsPkgs.persistent)
            (hsPkgs.persistent-sqlite)
            (hsPkgs.persistent-template)
            (hsPkgs.primitive)
            (hsPkgs.raw-strings-qq)
            (hsPkgs.resourcet)
            (hsPkgs.rio)
            (hsPkgs.rio-orphans)
            (hsPkgs.rio-prettyprint)
            (hsPkgs.safe)
            (hsPkgs.syb)
            (hsPkgs.tar-conduit)
            (hsPkgs.template-haskell)
            (hsPkgs.text)
            (hsPkgs.text-metrics)
            (hsPkgs.th-lift)
            (hsPkgs.th-lift-instances)
            (hsPkgs.th-orphans)
            (hsPkgs.th-reify-many)
            (hsPkgs.th-utilities)
            (hsPkgs.time)
            (hsPkgs.transformers)
            (hsPkgs.unix-compat)
            (hsPkgs.unliftio)
            (hsPkgs.unordered-containers)
            (hsPkgs.vector)
            (hsPkgs.yaml)
            (hsPkgs.zip-archive)
            ];
          };
        };
      };
    }