{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  {
    flags = {
      abi-assertions = true;
      optimize = true;
      optimize-aggressively = false;
      strict = false;
      strict-data = true;
    };
    package = {
      specVersion = "2.2";
      identifier = { name = "sdl3-bindgen-sys"; version = "0.0.0.1"; };
      license = "BSD-3-Clause";
      copyright = "(c) 2026 Jeremy Nuttall";
      maintainer = "jeremy@jeremy-nuttall.com";
      author = "Jeremy Nuttall";
      homepage = "https://github.com/jtnuttall/lithon#readme";
      url = "";
      synopsis = "Complete SDL3 bindings, raw + curated, generated by hs-bindgen";
      description = "Machine-generated low-level bindings to the whole SDL 3.4 API: the raw\nhs-bindgen output (@SDL3.Sys.Bindgen.*@) plus a curated @SDL3.Sys@ layer\nwith per-function safe/unsafe FFI decisions, typed constants, and native\nHaskell scalars. SDL's own header documentation rides along in the\nhaddocks.\n\nA generated translation unit of C @_Static_assert@s checks the baked\nlayouts against your installed SDL at every build, so ABI divergence is\na compile error rather than memory corruption.\n\nSupports 64-bit Linux, macOS, and Windows, with SDL >= 3.2 development\nheaders present. See the README for a quick start and the list of\ndeliberate omissions.";
      buildType = "Simple";
    };
    components = {
      "library" = {
        depends = [
          (hsPkgs."base" or (errorHandler.buildDepError "base"))
          (hsPkgs."sdl3-bindgen-sys".components.sublibs.bindgen-runtime or (errorHandler.buildDepError "sdl3-bindgen-sys:bindgen-runtime"))
          (hsPkgs."sdl3-bindgen-sys".components.sublibs.cexpr-runtime or (errorHandler.buildDepError "sdl3-bindgen-sys:cexpr-runtime"))
        ];
        pkgconfig = [
          (pkgconfPkgs."sdl3" or (errorHandler.pkgConfDepError "sdl3"))
        ];
        buildable = true;
      };
      sublibs = {
        "bindgen-runtime" = {
          depends = [
            (hsPkgs."base" or (errorHandler.buildDepError "base"))
            (hsPkgs."bytestring" or (errorHandler.buildDepError "bytestring"))
            (hsPkgs."containers" or (errorHandler.buildDepError "containers"))
            (hsPkgs."primitive" or (errorHandler.buildDepError "primitive"))
            (hsPkgs."record-hasfield" or (errorHandler.buildDepError "record-hasfield"))
            (hsPkgs."template-haskell" or (errorHandler.buildDepError "template-haskell"))
            (hsPkgs."vector" or (errorHandler.buildDepError "vector"))
          ];
          build-tools = [
            (hsPkgs.pkgsBuildBuild.hsc2hs.components.exes.hsc2hs or (pkgs.pkgsBuildBuild.hsc2hs or (errorHandler.buildToolDepError "hsc2hs:hsc2hs")))
          ];
          buildable = true;
        };
        "cexpr-runtime" = {
          depends = [
            (hsPkgs."base" or (errorHandler.buildDepError "base"))
            (hsPkgs."containers" or (errorHandler.buildDepError "containers"))
            (hsPkgs."fin" or (errorHandler.buildDepError "fin"))
            (hsPkgs."some" or (errorHandler.buildDepError "some"))
            (hsPkgs."template-haskell" or (errorHandler.buildDepError "template-haskell"))
            (hsPkgs."vec" or (errorHandler.buildDepError "vec"))
          ];
          buildable = true;
        };
      };
    };
  }