{ system, compiler, flags, pkgs, hsPkgs, pkgconfPkgs, ... }:
  {
    flags = {};
    package = {
      specVersion = "1.6";
      identifier = { name = "threadscope"; version = "0.2.0"; };
      license = "BSD-3-Clause";
      copyright = "2009-2010 Satnam Singh,\n2009-2011 Simon Marlow,\n2009 Donnie Jones,\n2011 Duncan Coutts,\n2011 Mikolaj Konarski";
      maintainer = "Satnam Singh <s.singh@ieee.org>";
      author = "Satnam Singh <s.singh@ieee.org>,\nSimon Marlow <marlowsd@gmail.com>,\nDonnie Jones <donnie@darthik.com>,\nDuncan Coutts <duncan@well-typed.com>,\nMikolaj Konarski <mikolaj.konarski@gmail.com>";
      homepage = "";
      url = "";
      synopsis = "A graphical tool for profiling parallel Haskell programs.";
      description = "ThreadScope is a graphical viewer for thread profile\ninformation generated by the Glasgow Haskell compiler\n(GHC).\n\nThe Threadscope program allows us to debug the parallel\nperformance of Haskell programs. Using Threadscope we can\ncheck to see that work is well balanced across the\navailable processors and spot performance issues relating\nto garbage collection or poor load balancing.";
      buildType = "Simple";
      };
    components = {
      exes = {
        "threadscope" = {
          depends = [
            (hsPkgs."base" or ((hsPkgs.pkgs-errors).buildDepError "base"))
            (hsPkgs."gtk" or ((hsPkgs.pkgs-errors).buildDepError "gtk"))
            (hsPkgs."cairo" or ((hsPkgs.pkgs-errors).buildDepError "cairo"))
            (hsPkgs."glib" or ((hsPkgs.pkgs-errors).buildDepError "glib"))
            (hsPkgs."pango" or ((hsPkgs.pkgs-errors).buildDepError "pango"))
            (hsPkgs."binary" or ((hsPkgs.pkgs-errors).buildDepError "binary"))
            (hsPkgs."array" or ((hsPkgs.pkgs-errors).buildDepError "array"))
            (hsPkgs."mtl" or ((hsPkgs.pkgs-errors).buildDepError "mtl"))
            (hsPkgs."filepath" or ((hsPkgs.pkgs-errors).buildDepError "filepath"))
            (hsPkgs."ghc-events" or ((hsPkgs.pkgs-errors).buildDepError "ghc-events"))
            (hsPkgs."containers" or ((hsPkgs.pkgs-errors).buildDepError "containers"))
            ] ++ (pkgs.lib).optional (!system.isWindows) (hsPkgs."unix" or ((hsPkgs.pkgs-errors).buildDepError "unix"));
          buildable = true;
          };
        };
      };
    }