{ compiler, flags ? {}, hsPkgs, pkgconfPkgs, pkgs, system }:
let
    _flags = {} // flags;
    in {
      flags = _flags;
      package = {
        specVersion = "1.10";
        identifier = {
          name = "typed-wire-utils";
          version = "0.1.0.0";
        };
        license = "BSD-3-Clause";
        copyright = "2015 Alexander Thiemann <mail@athiemann.net>";
        maintainer = "Alexander Thiemann <mail@athiemann.net>";
        author = "Alexander Thiemann";
        homepage = "http://github.com/typed-wire/hs-typed-wire-utils#readme";
        url = "";
        synopsis = "Haskell utility library required for code generated by typed-wire compiler";
        description = "Please see README.md";
        buildType = "Simple";
      };
      components = {
        typed-wire-utils = {
          depends  = [
            hsPkgs.base
            hsPkgs.aeson
            hsPkgs.bytestring
            hsPkgs.text
            hsPkgs.time
            hsPkgs.base64-bytestring
          ];
        };
      };
    }