{ compiler, flags ? {}, hsPkgs, pkgs, system }:
let
    _flags = {} // flags;
    in {
      package = {
        specVersion = "1.8";
        identifier = {
          name = "dx9base";
          version = "0.1.1";
        };
        license = "BSD-3-Clause";
        copyright = "";
        maintainer = "none";
        author = "Esa Ilari Vuokko";
        homepage = "";
        url = "";
        synopsis = "Backend for a binding to the Microsoft DirectX 9 API.";
        description = "This package provoide ComObject and some error types, to provide DirectX 9 Haskell binding.\nWe think replace some part by <http://hackage.haskell.org/cgi-bin/hackage-scripts/package/com>,\nor code what generated by <http://hackage.haskell.org/package/hdirect>.\n\nThis version requires DirectX SDK that is specified in --extra-include-dirs and --extra-lib-dirs PATH.\nSee the README file for more information.";
        buildType = "Simple";
      };
      components = {
        dx9base = {
          depends  = [
            hsPkgs.base
            hsPkgs.Win32
          ];
        };
      };
    }